name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rsfrontier-cli
            asset_name: rsfrontier-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rsfrontier-cli.exe
            asset_name: rsfrontier-windows-amd64.exe

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }} -p rsfrontier-cli

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            RSFrontier release ${{ github.ref_name }}
            
            ## Changes in this release
            
            <!-- Add release notes here -->

      - name: Save Release URL
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt

      - name: Upload Release URL artifact
        uses: actions/upload-artifact@v2
        with:
          name: release_url
          path: release_url.txt

  upload_assets:
    name: Upload Assets
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      matrix:
        include:
          - asset_name: rsfrontier-linux-amd64
            asset_content_type: application/octet-stream
          - asset_name: rsfrontier-windows-amd64.exe
            asset_content_type: application/octet-stream

    steps:
      - name: Download Release URL
        uses: actions/download-artifact@v2
        with:
          name: release_url

      - name: Get Release URL
        id: get_release_url
        run: echo "::set-output name=upload_url::$(cat release_url.txt)"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_url.outputs.upload_url }}
          asset_path: ./${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: ${{ matrix.asset_content_type }}